version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /tmp/db:/data/db:rw
  ertis:
    build: .
    links:
      - mongo
    ports:
      - "8888:8888"